spring:
  datasource:
    url: jdbc:mysql://gongbaek-backend-db-dev.cytmb3qvbtlr.ap-northeast-2.rds.amazonaws.com:3306/gongbaek?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gongbaek
    password: asdzxc1450
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:tcp://localhost/~/gongbaek;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate.type.BasicTypeRegistry: warn

jwt:
  access:
    secret.key: afdlsflkadklmlckamkldmflkamipejapiwiklsdmklmalkfsmklamlfmlkamdsfmaweijdlksmd
    expire.time: 100000000
  refresh:
    secret.key: afdlsflkadklmlckamkldmflkamipejapiwiklsdmklmalkfsmklamlfmlkamdsfmaweijdlqwer
    expire.time: 10000000000

aws:
  s3:
    academy:
      img:
        bucket: gongbaek.v1.backend
        dir: academy/img

      list:
        bucket: gongbaek.v1.backend
        dir: academy/list
