spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
#    url: {private for transition to public repository}
#    username: {private for transition to public repository}
#    password: {private for transition to public repository}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/gongbaek;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate.type.BasicTypeRegistry: warn

jwt:
  access:
    secret.key: afdlsflkadklmlckamkldmflkamipejapiwiklsdmklmalkfsmklamlfmlkamdsfmaweijdlksmd
    expire.time: 100000000
  refresh:
    secret.key: afdlsflkadklmlckamkldmflkamipejapiwiklsdmklmalkfsmklamlfmlkamdsfmaweijdlqwer
    expire.time: 10000000000

aws:
  s3:
    img:
      banner:
        bucket: gongbaek.static.io
        dir: banners
