spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gongbaek;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate.type.BasicTypeRegistry: warn

jwt:
  secretKey: fjdalkklamclkmalwefwajiejviajfilkamdlkdmclkmkadmkmfjwaeilkcmdlksmaclksmlk
  expiredTime: 1000

aws:
  s3:
    academy:
      img:
        bucket: gongbaek.v1.backend
        dir: academy/img

      list:
        bucket: gongbaek.v1.backend
        dir: academy/list
